parameters:
    locale: 'en'
    avatars_directory: '%kernel.project_dir%/public/web/img/avatars'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests, Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    StudentNormalizer:
        class: 'App\Serializer\Normalizer\StudentNormalizer'
        tags: [serializer.normalizer]
        arguments:
            - '@TeacherNormalizer'

    TeacherNormalizer:
        class: 'App\Serializer\Normalizer\TeacherNormalizer'
        tags: [serializer.normalizer]
        public: false